version: "3.5"

networks:
  event_driven_commerce:

services:
  db-customer:
    image: postgres:latest
    hostname: db-customer
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer_svc
    ports:
      - "5432:5432"
    volumes:
      - ./config/customer-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - event_driven_commerce

  db-product:
    image: postgres:latest
    hostname: db-product
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product_svc
    ports:
      - "15432:5432"
    volumes:
      - ./config/product-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - event_driven_commerce

  db-order:
    image: postgres:latest
    hostname: db-order
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order_svc
    ports:
      - "25432:5432"
    volumes:
      - ./config/order-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - event_driven_commerce
