version: "3.5"

networks:
  delivery:

services:
  db-customer:
    image: postgres:latest
    hostname: db-customer
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ddbb
    ports:
      - "5432:5432"
    volumes:
      - ./config/customer-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - delivery
