version: "3.5"

networks:
  event_driven_commerce:

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - event_driven_commerce

  db-customer:
    image: postgres:latest
    hostname: db-customer
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer_svc
    ports:
      - "5432:5432"
    volumes:
      - ./configs/customer-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - event_driven_commerce

  db-product:
    image: postgres:latest
    hostname: db-product
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product_svc
    ports:
      - "15432:5432"
    volumes:
      - ./configs/product-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - event_driven_commerce

  db-order:
    image: postgres:latest
    hostname: db-order
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=order_svc
    ports:
      - "25432:5432"
    volumes:
      - ./configs/order-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - event_driven_commerce

  db-payment:
    image: postgres:latest
    hostname: db-payment
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=payment_svc
    ports:
      - "35432:5432"
    volumes:
      - ./configs/payment-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    networks:
      - event_driven_commerce

  api-gtw:
    build:
      context: .
      dockerfile: ./apps/api-gtw/Dockerfile
    hostname: api-gtw
    environment:
      - PORT=8080
      - GRPC_HOST_PRODUCT_SVC=product-svc:50050
      - GRPC_HOST_CUSTOMER_SVC=customer-svc:50051
      - GRPC_HOST_ORDER_SVC=order-svc:50052
    depends_on:
      - product-svc
      - customer-svc
      - order-svc
    ports:
      - "8080:8080"
    networks:
      - event_driven_commerce

  customer-svc:
    build:
      context: .
      dockerfile: ./apps/customer-svc/Dockerfile
    hostname: customer-svc
    environment:
      - GRPC_PORT=50051
      - DATABASE_URL=postgresql://admin:admin@db-customer:5432/customer_svc
      - JWT_SECRET="COFFEE_BLEND"
    depends_on:
      - db-customer
    networks:
      - event_driven_commerce

  product-svc:
    build:
      context: .
      dockerfile: ./apps/product-svc/Dockerfile
    hostname: product-svc
    environment:
      - GRPC_PORT=50050
      - DATABASE_URL=postgresql://admin:admin@db-product:5432/product_svc
    depends_on:
      - db-product
    networks:
      - event_driven_commerce

  order-svc:
    build:
      context: .
      dockerfile: ./apps/order-svc/Dockerfile
    hostname: order-svc
    environment:
      - GRPC_PORT=50052
      - GRPC_HOST_PRODUCT_SVC=product-svc:50050
      - DATABASE_URL=postgresql://admin:admin@db-order:5432/order_svc
    depends_on:
      - db-order
      - product-svc
    networks:
      - event_driven_commerce

  payment-svc:
    build:
      context: .
      dockerfile: ./apps/payment-svc/Dockerfile
    hostname: payment-svc
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=postgresql://admin:admin@db-payment:5432/payment_svc
    depends_on:
      - rabbitmq
      - db-payment
    restart: on-failure
    networks:
      - event_driven_commerce
